### ISSUE TITLE
Lifecycle Questions

### ISSUE THREAD

**Issue by papo2608** [android10/Android-CleanArchitecture#10]
Hello,

could it be dangerous if Presenters and Interactors are defined as a Singelton? For example if I store the received data from the network in an instance variable of the Presenter, so that variable remains in memory for the hole application lifetime?

What happens if a network task needs for some some reasons more time as usually? Remains the view (Activity) of the Presenter in memory? Is there an advice when to clear it out?

**Comment by android10** [comment]
Saving state in singleton could be dangerous. I would not rely on the approach you mentioned. Android can kill your activity in any moment and you will loose the data.

You can always synchronize your data in disk periodically through scheduling requests and read always from there.

**Comment by papo2608** [comment]
Thank you for your response. Is there a reason why you don't clear the UserDetailsView out in the UserDetailsPresenter when the activity is destroyed? If I had understand that correctly, the Activity stays in memory until the thread finishes.

**Comment by papo2608** [comment]
And maybe you could tell me how do you handle the response of a request during a configuration change, wehen the requests finishes between onDestroy of the old activity an onCreate of the new activity? Do use a cache for such things?

**Comment by android10** [comment]
For now I'm just retaining the fragment instance. It works for now as I do not need more logic for the purpose of this learning example. There is a lot to discuss here and if you have a great idea, a pull request is very welcome :)

**Comment by papo2608** [comment]
I'm still searching for the Holy Grail in this case ;) and I thought you have solved that problem already in one of your applications, maybe you could tell us how you mange such things in you apps :).

**Comment by android10** [comment]
That depends on the case. I always use a cache and most of the time I have a sync service and query everything from diks
