### ISSUE TITLE
CompositeException -> getActivity().getApplicationContext() is null

### ISSUE THREAD

**Issue by spirosoik** [android10/Android-CleanArchitecture#102]
When a ```CompositeException``` occurred then the ```getActivity().getApplicationContext()``` (in getContext() method on each Fragment) or ```getContext()```(provided by support fragment) is null.

Not sure but I think it's related with this https://github.com/ReactiveX/RxAndroid/issues/21

**Comment by android10** [comment]
Can you write down the steps to reproduce this?

**Comment by android10** [comment]
@spirosoik I touched the code these days, so closing this issue until we can reproduce it. 
We can reopen it later ok? :smiley:

**Comment by spirosoik** [comment]
Yes of course :+1: . I will send the steps also.
