### ISSUE TITLE
JUnit version 3.8 or later expected

### ISSUE THREAD

**Issue by Fshamri** [android10/Android-CleanArchitecture#11]
Hi,
I am trying to learn from your code so i have started from domain module. I have copied build.gradle content of both  project and domain module also copied the buildsystem folder content from your project to mine. when i run a test case i got "JUnit version 3.8 or later expected"

I have cloned your repository and it works fine.. i am sure my project structure is similar to yours ..
I really don't know what is the problem in my project and how to solve it

**Comment by android10** [comment]
Cannot tell you much about your problem. This project is working as it is and I hope you understand that all the issues open are related to this project. I would suggest you to put the error with the whole trace on stackoverflow. Thanks.
