### ISSUE TITLE
Law of Demeter violation

### ISSUE THREAD

**Issue by papo2608** [android10/Android-CleanArchitecture#110]
If I have a UseCase which is e.g. calculating a price for a specific user and therefore I need do load the current user from the DB/FileSystem etc. I'm violating the Law of Demeter. I can still unit test the code but if a mock returns a mock it feels somehow wrong to me.

```java
public class CalculatePrice extends UseCase {

  private final UserRepository userRepository;
  private final PriceCalculator calculator;

  @Inject
  public GetUserList(UserRepository userRepository, PriceCalculator calculator, ThreadExecutor threadExecutor,
      PostExecutionThread postExecutionThread) {
    super(threadExecutor, postExecutionThread);
    this.userRepository = userRepository;
    this.calculator = calculator;
  }

  @Override public Observable buildUseCaseObservable() {
    return Observable.defer(() -> {
      User user = userRepository.getUser(); //call violates Law of Demeter
      BigDecimal price = calculator.calculate(user.getDiscount());
      return Observable.just(price);
    });
  }
}
```

What are your suggestions here? Should I'directly inject the User object to the UseCase by moving the call to the repo to my dagger module? If yes how can I guarantee, that the user data is up to date (the UseCase is inject in onCreate and executed later on?

**Comment by Trikke** [comment]
How exactly is the Law of Demeter broken here?
I'd imagine it would be broken if it was possible to do something like
`User user = userRepository.getDb().getUser()`

**Comment by papo2608** [comment]
Thanks for your reply. It's broken here user.getDiscount() and here user.getDiscount() because you are only allowed to talk to friends and if I call a method on a User object witch is fetch from another class I'm violating it. You don't think so?

**Comment by Trikke** [comment]
You are not applying LoD at the appropriate level: both User and UserRepository should be considered a part of the same module.

Your question is an example of a much wider problem, which I have frequently met in books on design patterns and similar: they try to explain wide-reaching principles, which concern the design of a complex system, on ridiculously undersized problems. The result is just reader's confusion.

Where you'd actually see this principle in effect is something like this: you are using AsyncHttpClient, which is an abstraction built atop Netty, which is an abstraction built atop Java NIO. Now, if AsyncHttpClient's API forced you at some place to directly manage a Java NIO object, whose API is much more raw, and deals with concepts completely foreign to AsyncHttpClient, that would be an example of breaking LoD.

**Comment by papo2608** [comment]
Thanks for clarification, your explanation sounds reasonable. But it still feels no 100% correct if for my unit tests  I've to return a mock from a mock.

**Comment by Trikke** [comment]
The Unit testing is another story. What are you actually testing here? Going from your name of your UseCase, i'd say you're actually trying to test that PriceCalculator to get the price with the user's discount. Because that is actually the only work that this UseCase does. So you write up a unit test for that PriceCalculator and inject MockUsers with different discounts into the test, and use that one.
I feel there's no need to mock the Repository here. It is not an important details for the test of the PriceCalculator. 

Even mocking a Repository pattern is another discussion. If the methods are trivial CRUD operations, all you're really testing is whether parameters are mapped correctly. If you have integration tests, such errors will become immediately apparent anyway.

**Comment by papo2608** [comment]
You're absolutely right, I just want to verify in that UT if getUser() was called and calculate() so I don't have any interactions with the user object. And of course I've a separate UT for the calculator. Thank you again for your clarification.
