### ISSUE TITLE
Where is the app package in the master branch??

### ISSUE THREAD

**Issue by Mun0n** [android10/Android-CleanArchitecture#111]
There is no "app" package in the master branch. I can found it in the other branch (core-refactor), but in the master branch that package is missing.

By the other hand in the "core-refactor" branch, the class "DaggerApplicationComponent" is missing too. So I can't compile the project.

Great project and great tutorial.

Thanks

**Comment by spirosoik** [comment]
@Mun0n It's not missing, it has just a different name according to the layers of the architecture. Instead of ```app``` there is the ```presentation``` module which is the same.

**Comment by lenguyenthanh** [comment]
@Mun0n About missing DaggerApplicationComponent: You should build the project then it appear.

**Comment by spirosoik** [comment]
+1 @lenguyenthanh

**Comment by Mun0n** [comment]
Thanks all!
