### ISSUE TITLE
NPE happened when running on Android 4.4

### ISSUE THREAD

**Issue by Synix** [android10/Android-CleanArchitecture#113]
Hi, when i tried to run this project on my android 4.4 device, I got a NPE crash:

E/AndroidRuntime(18300): FATAL EXCEPTION: main
E/AndroidRuntime(18300): Process: com.fernanependocejas.android10.sample.presentation, PID: 18300
E/AndroidRuntime(18300): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.fernanependocejas.android10.sample.presentation/com.fernandocejas.android10.sample.presentation.view.activity.UserListActivity}: java.lang.NullPointerException
E/AndroidRuntime(18300): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2184)
E/AndroidRuntime(18300): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2233)
E/AndroidRuntime(18300): 	at android.app.ActivityThread.access$800(ActivityThread.java:135)
E/AndroidRuntime(18300): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196)
E/AndroidRuntime(18300): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime(18300): 	at android.os.Looper.loop(Looper.java:136)
E/AndroidRuntime(18300): 	at android.app.ActivityThread.main(ActivityThread.java:5001)
E/AndroidRuntime(18300): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime(18300): 	at java.lang.reflect.Method.invoke(Method.java:515)
E/AndroidRuntime(18300): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
E/AndroidRuntime(18300): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
E/AndroidRuntime(18300): 	at dalvik.system.NativeStart.main(Native Method)
E/AndroidRuntime(18300): Caused by: java.lang.NullPointerException
E/AndroidRuntime(18300): 	at com.fernandocejas.frodo.aspect.LogObservable.methodAnnotatedWithRxLogObservable(LogObservable.java:27)
E/AndroidRuntime(18300): 	at com.fernandocejas.android10.sample.data.net.RestApiImpl.userEntityList(RestApiImpl.java)
E/AndroidRuntime(18300): 	at com.fernandocejas.android10.sample.data.repository.datasource.CloudUserDataStore.userEntityList(CloudUserDataStore.java:51)
E/AndroidRuntime(18300): 	at com.fernandocejas.android10.sample.data.repository.UserDataRepository.users(UserDataRepository.java:54)
E/AndroidRuntime(18300): 	at com.fernandocejas.android10.sample.domain.interactor.GetUserList.buildUseCaseObservable(GetUserList.java:41)
E/AndroidRuntime(18300): 	at com.fernandocejas.android10.sample.domain.interactor.UseCase.execute(UseCase.java:60)
E/AndroidRuntime(18300): 	at com.fernandocejas.android10.sample.presentation.presenter.UserListPresenter.getUserList(UserListPresenter.java:115)
E/AndroidRuntime(18300): 	at com.fernandocejas.android10.sample.presentation.presenter.UserListPresenter.loadUserList(UserListPresenter.java:79)
E/AndroidRuntime(18300): 	at com.fernandocejas.android10.sample.presentation.presenter.UserListPresenter.initialize(UserListPresenter.java:70)
E/AndroidRuntime(18300): 	at com.fernandocejas.android10.sample.presentation.view.fragment.UserListFragment.loadUserList(UserListFragment.java:158)
E/AndroidRuntime(18300): 	at com.fernandocejas.android10.sample.presentation.view.fragment.UserListFragment.onViewCreated(UserListFragment.java:80)
E/AndroidRuntime(18300): 	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:904)
E/AndroidRuntime(18300): 	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1062)
E/AndroidRuntime(18300): 	at android.app.BackStackRecord.run(BackStackRecord.java:684)
E/AndroidRuntime(18300): 	at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1447)
E/AndroidRuntime(18300): 	at android.app.Activity.performStart(Activity.java:5240)
E/AndroidRuntime(18300): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2157)
E/AndroidRuntime(18300): 	... 11 more

**Comment by Synix** [comment]
I switch to Android 6.0 device, then this crash issue is gone...

**Comment by Rainer-Lang** [comment]
@Synix But this issue still exists for Android 4.4?
