### ISSUE TITLE
Is every user action correspond to an usecase, and every usecase correspond to a class file?

### ISSUE THREAD

**Issue by wzxwater** [android10/Android-CleanArchitecture#128]
We can see 2 example usecase in the code : `GetUserList ` and `GetUserDetails`.
if I have 3 new user's action like: `CreateUser`, `DelectUser`,  `NotifyUserDetails`, it means i need to create 3 usecase ?

With the increasing complexity of the project, It will have large number of usecase .And every usecase  correspond to a class.Will cause too many class files in the project?

**Comment by lenguyenthanh** [comment]
I don't think it will increasing complexity of the project but it will decreasing the complexity instead. Image that when you look into a project and you find those classes:  `CreateUser`, `DelectUser`, `NotifyUserDetails`. You will understand what stuff does the project work on. For your example, you will see that project does something with user like: create, delete, etc.

**Comment by binhbt** [comment]
More class but not more complexity @wzxwater

**Comment by wzxwater** [comment]
Is it follow the single responsibility principle? one class do one thing.⊙０⊙
@lenguyenthanh @binhbt 

I usually will code like this:
```
interface UserBiz{
    Observable<List<User>> getUserList();
    Observable<User> getUserDetail((int userId);
    Observable<User> createUser(User user);
    Observable<User> delectUser(int userId);
    Observable<User> notifyUserDetails(User user);
}
```

it looks like more Strong cohesion.All the user related action in one class.

**Comment by lenguyenthanh** [comment]
@wzxwater: yep, SRP is one class does one thing. So one Usecase class should do only one thing. Your inteface UserBiz should be use for API instead of Usecase class.
