### ISSUE TITLE
(domain layer) : Command pattern and parameters

### ISSUE THREAD

**Issue by lutaseb** [android10/Android-CleanArchitecture#129]
```
myUseCase.execute(subscriber)
```
is ok if you have a module that injects a user's data at instanciation time, like in the example project.
But what if I have to display the result of this query in the same view, I mean if I don't have a screen/view dedicated for this particular user, I have a list of users and on the same view I want to display a user's info.
Since I certainly won't create a module everytime I click on a user in the list, and I don't think it is possible for dagger to take "outside" parameters to have something like
```
provideUseCase(int userId)...
```
I just wrote something like 
```
setup(int userId)
```
in order to keep the
```
execute(subsrciber)
```
intact..
any though on this?

**Comment by wzxwater** [comment]
I have the same question about than.
```
public class GetUserDetails extends UseCase {

  private final int userId;
  private final UserRepository userRepository;

  @Inject
  public GetUserDetails(int userId, UserRepository userRepository,
      ThreadExecutor threadExecutor, PostExecutionThread postExecutionThread) {
    super(threadExecutor, postExecutionThread);
    this.userId = userId;
    this.userRepository = userRepository;
  }

  @Override protected Observable buildUseCaseObservable() {
    return this.userRepository.user(this.userId);
  }
}
```

in this usecase, the parameter `userId`  is initalize in the constructor.and the `GetUserDetails` will instance when fragment `onCreate` call.


If i have another usecase like:

```

public class NotifyUserDetails extends UseCase {

  private final int userId;
  private final String name;
  private final int age;
  private final UserRepository userRepository;
  @Inject
  public NotifyUserDetails(int userId, String name, int age, UserRepository userRepository,
      ThreadExecutor threadExecutor, PostExecutionThread postExecutionThread) {
    super(threadExecutor, postExecutionThread);
    this.userId = userId;
    this.name = name;
    this.age = age;
   
    this.userRepository = userRepository;
  }

  @Override protected Observable buildUseCaseObservable() {
    return this.userRepository.notify(userId, name, age);
  }
```

I want to get `name`  and `age`  in edittext as  parameter deliver to `NotifyUserDetails`, then execute this usecase in `submit` button click. 

felling so contradictions! 


How can i delivier the parameter to the usecase after it instance?

**Comment by lenguyenthanh** [comment]
@wzxwater we have similar issue here #32 Hope you can find your answer.

**Comment by lutaseb** [comment]
@lenguyenthanh thanks, I just commented the issue which reflect the same kind of issue (even if it s closed), thanks
