### ISSUE TITLE
Dagger 2 scopes explanation under the hood

### ISSUE THREAD

**Issue by CROSP** [android10/Android-CleanArchitecture#137]
Hi, sorry for creating an issue,  but I have not place to ask such question. 
I am trying to understand `Dagger2` scope mechanism. 
Please correct me if I am wrong.
Dagger 2 by default has only one `Scope` that it can recognize and it is `@Singleton`. When graph is being built when dagger 2 meets this annotation it makes this object be cached during all application lifecycle, so whenever you injecting dependencies it returns the same instance that was created when first inject occurred. 
All other annotations doesn't make any sense to dagger graph builder, it just skips them ? 
Everything but `@Singleton` is ignored by Dagger 2, am I right ? 
I don't understand how life of component is managed ? I have only one idea 
1. When you use `@Singleton` annotation dagger is creating object in some static pool that will exists during whole application lifecycle, and will be destroyed when JVM process (dalvik VM,ART) instance will be destroyed.
2. When you use any other annotation is just for you as developer to better maintain code, `@PerActivity`, `@PerFragment` is just custom annotation nothing more. And in case you place `@PerFragment` component in Application class it will live as long as Application lives. Am I right
3. So I understand this like this, if dagger finds `@Singleton` annotation it will add static reference to component when it is created first time and in case of any other annotation it won't hold reference to component.

I would be grateful for any help.

**Comment by BillBosiolis** [comment]
Hi CROSP,

You can read this great blog post to have a detailed idea about how scoped components work in dagger 2

http://frogermcs.github.io/dependency-injection-with-dagger-2-custom-scopes/

In a few words Dagger does not ignore scoped annotations at all. It was a bit cryptic for me too at the beginning. It will inject for you the same instance ("local" singleton) as long as the component you use is still "alive".

Note that this blog is also accompanied with a sample application

https://github.com/frogermcs/GithubClient/blob/master/README.md

I hope that helps.

**Comment by CROSP** [comment]
Thank you for answer, I have already ready read this post several times, but still cannot get how dagger manages scopes.

**Comment by CROSP** [comment]
Can someone explain how lifetime is managed by dagger, and how does it know which object to tie lifecycle to ? We do not specify any annotation that directs dagger to use exactly this object as indication of lifetime of component. We can call our component as we want and annotate with any custom annotation. I tried even explore dagger2 source code, but it is quite difficult to understand for me.

**Comment by farmazon3000** [comment]
Your question does not belong to this project so I'd rather suggest to ask it somewhere else, e.g. in https://github.com/google/dagger.

**Comment by android10** [comment]
@farmazon3000 👍 I'm closing this issue since it is framework related and does not belong to here.
