### ISSUE TITLE
Fatal error java.lang.Verify during getting users list on Samsung devices with Android version less than 5

### ISSUE THREAD

**Issue by filatoff** [android10/Android-CleanArchitecture#142]
During get users from API on Samsung devices with Android < 5 always throwing fatal error. 

Reproduces on devices:
 - Samsung GT-i9300, Android 4.4.4
 - Samsung SM-T530, Android 4.4.2
 - Samsung Nexus S, Android 4.1.2

On Samsung SM-G531F, Android 5.1.1 worked correctly

May be bug reproduced for all devices on Android < 5 (no-samsung devices with v4.. not available for me).

Error listing:
> E/AndroidRuntime: FATAL EXCEPTION: main
> Process: com.fernanependocejas.android10.sample.presentation, PID: 31028
> java.lang.VerifyError: com/fernandocejas/android10/sample/data/net/RestApiImpl$AjcClosure1
>   at com.fernandocejas.android10.sample.data.net.RestApiImpl.userEntityList(RestApiImpl.java:53)
>   at com.fernandocejas.android10.sample.data.repository.datasource.CloudUserDataStore.userEntityList(CloudUserDataStore.java:51)
>   at com.fernandocejas.android10.sample.data.repository.UserDataRepository.users(UserDataRepository.java:54)
>   at com.fernandocejas.android10.sample.domain.interactor.GetUserList.buildUseCaseObservable(GetUserList.java:41)
>   at com.fernandocejas.android10.sample.domain.interactor.UseCase.execute(UseCase.java:60)
>   at com.fernandocejas.android10.sample.presentation.presenter.UserListPresenter.getUserList(UserListPresenter.java:115)
>   at com.fernandocejas.android10.sample.presentation.presenter.UserListPresenter.loadUserList(UserListPresenter.java:79)
>   at com.fernandocejas.android10.sample.presentation.presenter.UserListPresenter.initialize(UserListPresenter.java:70)
>   at com.fernandocejas.android10.sample.presentation.view.fragment.UserListFragment.loadUserList(UserListFragment.java:158)
>   at com.fernandocejas.android10.sample.presentation.view.fragment.UserListFragment.onViewCreated(UserListFragment.java:80)
>   at android.app.FragmentManagerImpl.moveToState(FragmentManager.java)
>   at android.app.FragmentManagerImpl.moveToState(FragmentManager.java)
>   at android.app.BackStackRecord.run(BackStackRecord.java)
>   at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java)
>   at android.app.Activity.performStart(Activity.java)
>   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java)
>   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java)
>   at android.app.ActivityThread.access$800(ActivityThread.java)
>   at android.app.ActivityThread$H.handleMessage(ActivityThread.java)
>   at android.os.Handler.dispatchMessage(Handler.java)
>   at android.os.Looper.loop(Looper.java)
>   at android.app.ActivityThread.main(ActivityThread.java)
>   at java.lang.reflect.Method.invokeNative(Native Method)
>   at java.lang.reflect.Method.invoke(Method.java:515)
>   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java)
>   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java)
>   at dalvik.system.NativeStart.main(Native Method)

**Comment by filatoff** [comment]
Important Note: 
Bug passed after update to Android Studio 2.
On Android Studio 1.5 app worked correctly.

**Comment by android10** [comment]
@filatoff any solution? Maybe a PR?

**Comment by filatoff** [comment]
@android10 I can`t understand what went wrong. May be it`s a bug of Android Studio 2. 
I can`t resolve this bug accordingly i wrote this issue. Probably, somebody know )

**Comment by binhbt** [comment]
Today i upgrade android studio to 2.0 and got this issue @filatoff  :dash:

**Comment by android10** [comment]
@filatoff @binhbt it is working for me. Also try via command line, if that works, probably it is an Android Studio issue.

**Comment by DashingRaj** [comment]
I also got this error on Android 2.1.1 and tried everything but no use
Then I change the gradle build tool version to back 1.5.0 from 2.1.0 updated by Android studio now it is working fine

**Comment by android10** [comment]
@DashingRaj have you tried compiling using the command line?

**Comment by binhbt** [comment]
I don't know why but when i change 
  compileOptions {
    sourceCompatibility JavaVersion.VERSION_1_8
    targetCompatibility JavaVersion.VERSION_1_
  }
to 
  compileOptions {
    sourceCompatibility JavaVersion.VERSION_1_7
    targetCompatibility JavaVersion.VERSION_1_7
  }
in data build.grade It work perfect.
Hope this help :v:
