### ISSUE TITLE
How to generate a single apk to run on devices

### ISSUE THREAD

**Issue by deserthero** [android10/Android-CleanArchitecture#157]
Now i works with this amazing clean architecture for a month, i almost finalise all the work i need, generated signed certificate for release vesrsin and now i want to generate an apk to test send it to the client to check.

but when i take this apk:  presentation-release.apk and run it on the mobile i faced an error, but when i run the apk through android studio to install it on the connected device it works well.

I notice that android studio install apk with this command:

```
$ adb push C:\[projectpath]\presentation\build\outputs\apk\presentation-release.apk /data/local/tmp/com.mypackage.presentation
$ adb shell pm install -r "/data/local/tmp/com.deserthero.memorylayers.mypackage.presentation"
```

So how can i generate a single apk to distribute it and install it on devices

**Comment by android10** [comment]
It works for me when I build the project and use the mentioned apk in the output folder.
