### ISSUE TITLE
Correct class for userComponent instance variable

### ISSUE THREAD

**Issue by khashish** [android10/Android-CleanArchitecture#160]
Currently the userComponent instance variable in the UserActivityList class is recreated every time the activity is created. So lets say the user entered the UserActivityList, userComponent will be created and it will be used in UserListFragment for injection. Lets say that the user rotated his screen, the userComponent variable now will be recreated again and since UserListFragment is retained then my understanding is that the new instance of userComponent will be useless in that case(since it won't be used again for injection).

- My question is why do we have userComponent as an instance variable in the activity rather than declaring it as an instance variable in the fragment since it's used there already for injection and in that case no useless instance of userComponent will be created every time the user rotates his device since the fragment is retained?

**Comment by android10** [comment]
This is a good point. A PR is very welcome dough 😃
