### ISSUE TITLE
Models boilerplate and login token expiration questions

### ISSUE THREAD

**Issue by grede** [android10/Android-CleanArchitecture#164]
Hi all Clean Architecture lovers :)
Thanks to Fernando for great articles and this repository.

I have 2 questions and any help would be much appreciated:

1) Why do we have to use 3 different classes to represent basically the same object? I'm talking about **User** from the domain, **UserModel** from the presentation, and **UserEntity** from the data layers. I understand that according to the Clean Architecture approach those classes must be separated as they belong to different layers and we should use mappers to convert from one model to another. But isn't it too much boilerplate code? It doesn't hurt when we have a few models across the app, but in large project I would use a lot of models and it is going to be a huge number of repeated classes (ok, maybe almost repeated).

2) Let's say we have an app and its main activity has two fragments divided into tabs. Upon activity start both fragments begin their work simultaneously. First fragment loads a news feed update **`List<News>`** using a **GetNewsInteractor** interactor, second fragment attempts to load a list of some articles **`List<Article>`** using a **GetArticlesInteractor**. Both interactors rely on some network based **CombinedAPI** defined in the data layer. Also both interactors use a **token** to reach the API (let's say we received and saved it locally in the repository on the login screen). So both interactors start network requests at the same time and then realize that the token **has expired**. What should the app do if it have login & password saved locally (user clicked on "save password" during login) ? My though was to perform a re-login in the background to refresh the token. Is it ok for GetNewsInteractor / GetArticlesInteractor to call the **LoginInteractor** directly ? If so, how do I handle it so they do not login twice at the same time? Synchronize LoginInteractor somehow?

Thanks in advance.

**Comment by Trikke** [comment]
1) You seem to understand the point. We're talking about the same "thing" (ie a User) but this thing is represented differently in each layer. I understand some people view this as repeated classes, but you must see that each Object in each layer can be more than just a class with some fields. A **UserViewModel** in the Presentation Layer may have a method to show a pretty user name. A **UserEntity** in the Data layer may have methods to increment id's used in the local DB system. **UserModel** in the Domain Layer may have validation logic that is crucial with the business rules of your app and is used by a lot of interactors. And of course, there's load of mapping libs out there to automate a lot of mapping code.

2) Leaving the whole app example out for a bit (but it's nice to give us an example of what you had in mind) there are a few things here : 

- Never call interactors from other interactors. An interactor is just a specific Use Case, like "get the article list", "log in the user". It's just a flow of business rules to meet the goal of the Use Case. And in the domain layer, there's more than just Use Cases. The whole "re-authenticate" flow is never a simple one, and can be tackled in many forms. If there's logic that seems to be shared between Use Cases, it makes sense to have a common component and include that for use by both. So in your case, you'd have something like a "Authorisation Manager". It handles the logic for logging in, or relogging in. And both use cases would have a reference to this. So if an interactor gets a response back that the token has expired, it gets a new one via the manager and tries it's call again. You can make the manager smart enough to hold any subsequent login calls if one is already running and return it's response to everyone. Another way is that authentication is actually a deep part of your API. And it detects if a response requires a re login and does a log in call, followed by the original call. This way, the interactors have no idea that a re-login happened.
- Just a side note, never save the user's actual password. Have it hashed and never pass it anywhere in clear text.

**Comment by grede** [comment]
@Trikke that's a great explanation, thanks a lot!

> Just a side note, never save the user's actual password. Have it hashed and never pass it anywhere in clear text.

sure thing, I meant some kind of hash of password of course :)

**Comment by beetlewar** [comment]
> * Authorisation Manager

If we talk about clean architecture, could you please explain which layer does this manager belongs to?
