### ISSUE TITLE
关于data层 datafractory的疑问

### ISSUE THREAD

**Issue by chaozaiai** [android10/Android-CleanArchitecture#167]
data层，示例代码里就只是一个user数据的网络获取和本地缓存，建立了一个userdatafactory,比如又有了新闻数据，天气数据等。那有几个数据就建立几个对应的datafactory吗？我现在是想把多个数据源都放在一个factory ，但是发现判断缓存是否过期和是否已经缓存不知道怎么处理，所以能指点下吗？

**Comment by chaozaiai** [comment]
https://github.com/googlesamples/android-architecture/tree/todo-mvp-clean/  因为这个里面没有网路请求相关的部分。所以我根据这个和现在android10的示例，结合起来，去掉了mapper相关数据转换的部分，感觉两者思路大致一样，但是写法上却有不同，现在有点晕了。
这是我写的代码，现在正在增加本地缓存的部分，写着写着，就更晕了。

**Comment by lenguyenthanh** [comment]
Could you english please?

**Comment by RowlandOti** [comment]
Haha, @lenguyenthanh  , it is Chinese to be begged to English!

**Comment by android10** [comment]
Closing since we cannot help here @chaozaiai until this is translated to english. Sorry.
