### ISSUE TITLE
Duplicate UseCase for different view logic

### ISSUE THREAD

**Issue by enuoCM** [android10/Android-CleanArchitecture#176]
Just a silly example with two view logic. If click the first button, it will display a dialog with the message "Say 'Yes' to XX users?", where XX is the count of current uses. And if click the second button, it will display a dialog with the message "Say 'No' to XX users?". Suppose we can click button 1 then click button 2 quickly, and display two dialogs at last. So dose it have to inject two 'Get count of user" UseCases with different callbacks or subscribers to the presenter? What about five, ten similar UseCases?

**Comment by android10** [comment]
You can reuse code through inheritance or composition: always favor composition over inheritance.

**Comment by enuoCM** [comment]
@android10 Thanks. Yes, I can reuse code through composition. But for the special example, all I need is a simple  'Get count of user" UseCase. Is it true that it need two instances of the same UseCase for the two button click event?

**Comment by android10** [comment]
Yes, you will be creating a new instance every time the user clicks the button ;)

**Comment by ZherebtsovAlexandr** [comment]
Hi @android10 !

How can I use the composition in this case?

I have three interactors:

```
public class GetBusList extends UseCase {

    ...  
    
    @Override
    protected Observable buildUseCaseObservable() {
       // return very big observable
    }
    
}
```

```
public class GetCarList extends UseCase {

    ...  
    
    @Override
    protected Observable buildUseCaseObservable() {
       // return very big observable
    }
    
}
```

```
public class GetTrainList extends UseCase {

    ...  
    
    @Override
    protected Observable buildUseCaseObservable() {
       // return very big observable
    }
    
}
```

I need do in fourth interactor:

```
Observable.zip(busObservable, carObservable, trainObservable, new Func3<List<Vehicle>, List<Vehicle>, List<Vehicle>, List<Vehicle>>() {
                                @Override
                                public List<Vehicle> call(List<Vehicle> busList,
                                                           List<Vehicle> carList,
                                                           List<Vehicle> trainList){
                                    ...
                                    return merged;
                                }
                            }
```


I need directly access to Observables in UseCase's here?
