### ISSUE TITLE
is com.fernandocejas.android10.sample.data.entity.mapper violated Dependency Rule?

### ISSUE THREAD

**Issue by haipv-ptit** [android10/Android-CleanArchitecture#181]
Hello,
I have a question want to clear
Are  UserEntityDataMapper and UserEntityJsonMapper  (in package com.fernandocejas.android10.sample.data.entity.mapper) violated dependency rule: "_Nothing in an inner circle can know anything at all about something in an outer circle_" (refer: https://8thlight.com/blog/uncle-bob/2012/08/13/the-clean-architecture.html)?.
For example: UserEntityDataMapper mapping from UserEntity (inner circle) to User (outer circle)

> public User transform(UserEntity userEntity) {
>     User user = null;
>     if (userEntity != null) {
>       user = new User(userEntity.getUserId());
>       user.setCoverUrl(userEntity.getCoverUrl());
>       user.setFullName(userEntity.getFullname());
>       user.setDescription(userEntity.getDescription());
>       user.setFollowers(userEntity.getFollowers());
>       user.setEmail(userEntity.getEmail());
>     }
>     return user;
>   }

The inner circle(Data) know all about User class in outer circle (Domain) .
Thanks alots

**Comment by takuaki** [comment]
I think the innermost layer is domain-layer, so mapping UserEntity to User  is ok.
