### ISSUE TITLE
A question regarding navigation

### ISSUE THREAD

**Issue by mglee72** [android10/Android-CleanArchitecture#19]
Hi, thank you for a fantastic example app.

I notice that you are using a custom Navigator class for launching activities (with arguments and so forth). I would like to know how you would integrate Navigator class into `startActivityForResult` and `onActivityResult` use case.

I could think of a few options for decoupling these "View" classes. i.e. `ActivityA` starting `ActivityB` by creating `Intent` with direct reference to `Activity B`
1. Ditching this whole "ForResult" idea altogether.
2. Introducing "callbacks" which would be called in DestinationActivity before finishing.
3. Navigator supplying `navigateToSomeActivity(... int requestCode);` and calling `Activity`/`Fragment` handles the results via plain old `onActivityResult`

I am leaning more towards option 3, but I would love to know more of your opinions (and possible implementations in this example in the future maybe?).

Thanks a lot.

**Comment by android10** [comment]
Although navigation is out of the scope of this example, number 3 could be a good option. If you come up with a solution to the problem, maybe would be a good idea to include it :).

**Comment by mglee72** [comment]
I haven't found a clear-cut satisfying solution yet, but i think navigation maybe is worth giving a look into. I recently came across VIPER (iOS version of Clean Architecture) which includes "R"outing (navigation), but I feel that navigation/routing is very platform-oriented thus not quite suitable for a single cookbook solution. Anyways, thank you for your input. I will further contemplate upon this issue.

**Comment by android10** [comment]
@mglee72 Definitely navigation is platform oriented but I did not want this sample to grow that much and be focused on the architecture itself and how presenters, use cases and different layers live together. Mainly due to the lack of time :), but as I said, pull requests are always welcome to review if you come up with a solution :).
