### ISSUE TITLE
How to pass parameters to use-case correctly?

### ISSUE THREAD

**Issue by memfis19** [android10/Android-CleanArchitecture#190]
I just want to clarify what is the right way to pass parameters into use-case. In current example we pass 'userId' via constructor and we know it before we create 'UserComponent'. In case we have another situation i.e. 'Login', we know login/password only after user clicks login button so we can't pass them in such way. So what is best option to do it?

**Comment by maoueh** [comment]
Check out https://github.com/android10/Android-CleanArchitecture/issues/32

**Comment by memfis19** [comment]
Thank you very much!
