### ISSUE TITLE
Question about license

### ISSUE THREAD

**Issue by asyncee** [android10/Android-CleanArchitecture#196]
Hello! I'm java and android beginner and i want to start with clean architecture.

I think this project example fits my needs, so i got a question: can i use a copy of your source code (or parts of source code file / single files) in my project without specifying a copy of current license (Apache 2.0 and copyrights)?

For example, can i use your class ErrorBundle in my own project without copyright and license text in it?

I do not want to violate the license and i have read about Apache 2.0, but it is not clear to me yet.

My project is non commercial; but question covers commercial projects also (proprietary, not open sourced).

Thanks!

**Comment by android10** [comment]
You can do anything you want with the code but AFAIK you should keep the license and author of the classes.

**Comment by fanky10** [comment]
Can we close this? so we clean up the issue list a little bit.

**Comment by asyncee** [comment]
Thank you for information, sorry for late response. Closing.

**Comment by npestana** [comment]
Sorry for reopening this issue. There are some files that still have the old license and others without license. For example, [BaseActivity.java](https://github.com/android10/Android-CleanArchitecture/blob/7339de70e1d691b8f24b9ca0472536dc24838b96/presentation/src/main/java/com/fernandocejas/android10/sample/presentation/view/activity/BaseActivity.java) has no license and [BaseFrament.java](https://github.com/android10/Android-CleanArchitecture/blob/7339de70e1d691b8f24b9ca0472536dc24838b96/presentation/src/main/java/com/fernandocejas/android10/sample/presentation/view/fragment/BaseFragment.java) has the old license. The repository license (Apache 2.0) applies to these files too?

Thank you!

**Comment by android10** [comment]
@npestana if they have no license it is because I forgot it 😄 
The license is Apache 2.0 as it says in the README file

**Comment by npestana** [comment]
@android10 what about files with this [license](https://github.com/android10/Android-CleanArchitecture/blob/7339de70e1d691b8f24b9ca0472536dc24838b96/presentation/src/main/java/com/fernandocejas/android10/sample/presentation/view/fragment/BaseFragment.java#L2)? Apache 2.0 too?

Thank you!
