### ISSUE TITLE
Question about testing

### ISSUE THREAD

**Issue by jemshit** [android10/Android-CleanArchitecture#200]
Hi, i have general question. I have checked test code. 

In Data layer test, **test class only tests if some method is called, and does not care about result of method**. Example, RepositoryTest only tests if method for getting User object is called, but it does not check if it really gets User object from that method. Same for DataStore classes. 

In Domain layer, again same thing for UseCases. It only tests if UseCase calls some repository method. Does not care about if it really gets result from that method.

In Presentation layer, again PresenterTest only tests if Presenter calls some method of UseCase. 

**Question:**
1) What is point of "testing only if method is invoked" :grey_question:
2) Why none of the Test classes care about the result of method they've called :grey_question: Example, Presenter only checks if it calls useCase method, but why it does not check if view.showContent() is called after useCase returns data? There is no test for if UserCache is able to return right data? 

Sorry if i am missing sth

**Comment by humblerookie** [comment]
https://static.javadoc.io/org.mockito/mockito-core/1.10.19/org/mockito/ArgumentCaptor.html

**Comment by jungornti** [comment]
This is simple — you need to test the **behaviour**, not the implementation. If you test agains interface, you test behaviour, so you only need to know if the method is actually called.

How this method behaves and what data returns you should test when writing concrete implementation.

**Comment by jemshit** [comment]
@jungornti 
> How this method behaves and what data returns you should test when writing concrete implementation.
What do you mean? There is Presenter implementation class which calls UseCase methods, still it doesn't check data returned

**Comment by jungornti** [comment]
If you testing presentation layery (Presenter) then you dont care about data, that comes from UseCase, because you should care about use case being called at all.

You should care about data in following situations (for example):
1. if you testing repository or datasource implementation
2. if you testing your aggregate root or domain service to test if all invariants are correct.

**Comment by jemshit** [comment]
@jungornti ok, then where is the test that tests data returned from UseCase? For example, i want to test after executing UseCase, is presenter really calling `view.showError()` etc, like this line: https://github.com/android10/Android-CleanArchitecture/blob/master/presentation/src/main/java/com/fernandocejas/android10/sample/presentation/presenter/UserDetailsPresenter.java#L113

How to test that exact line?

**Comment by jungornti** [comment]
I think that this test is missing. You can check [https://codelabs.developers.google.com/codelabs/android-testing/#0](this google codelab), maybe it will help.

Now, about testing this exact line. First of all, i will test that presenter calls `showErrorMessage` with any string (i dont care about text for now).

Then i will test that usecase throws correct exception if there are any specific case for that.

Then i will test method `showErrorMessage` itself, by passing hand−crafted test ErrorBundle.

**Comment by jemshit** [comment]
What about if there was this line `this.viewDetailsView.showError(errorMessage);` in line 113, inside onError(),  presenter calls view method directly ? How would you test it?

**Comment by youranshul** [comment]
@jemshit you can mock the view interface (viewDetailsView) in your presenter test class and can use mockito to verify if that method gets called or not .

presenter.someServerCall();
and that call returns the callback on OnError() you can verfiy if the showError method is called or not.
Mockito.verify(viewDetailsView).showError(anyString())

**Comment by jemshit** [comment]
thanks guys
