### ISSUE TITLE
TestCases failing when testing presenters

### ISSUE THREAD

**Issue by cheflingAnsh** [android10/Android-CleanArchitecture#204]
Hi @android10 I am following the same structure for my app where i am trying to test the presenter but the test case is failing due to the arguments mismatch.
Here is the test class 
`public class TaskPlannerPresenterShould {
    @Rule
    public MockitoRule mockitoRule = MockitoJUnit.rule();
    @Mock
    private UseCase<Boolean, Void> selfUpdate;

    private TaskPlannerPresenter presenter;

    @Before
    public void setUp() {
        MockitoAnnotations.initMocks(this);
        presenter = new TaskPlannerPresenter(selfUpdate);
    }

    @Test
    @SuppressWarnings("unchecked")
    public void processSelfUpdate() throws Exception {
        presenter.processSelfUpdate();
        Mockito.verify(selfUpdate).execute(any(DisposableObserver.class), any(Void.class));

    }
}`

This is the call from presenter 
`public class TaskPlannerPresenter implements Presenter {

    private static final String TAG = TaskPlannerPresenter.class.getSimpleName();
    @Inject
    Log log;
    private final UseCase<Boolean, Void> selfUpdate;

    @Inject
    public TaskPlannerPresenter(UseCase interactor) {
        this.selfUpdate= selfUpdate;
        // log.i(TAG, "TaskPlannerPresenter :");
    }

    public void processSelfUpdate() {
        selfUpdate.execute(new SelfUpdateObserver(), null);
    }

    private final class SelfUpdateObserver extends DefaultObserver<Boolean> {
        @Override
        public void onNext(Boolean value) {
            log.i(TAG, "SelfUpdate Result :" + value);
        }

        @Override
        public void onError(Throwable e) {

        }

        @Override
        public void onComplete() {

        }
    }
}`

But the test case fails with the error 
`Argument(s) are different! Wanted:
selfUpdateInteractor.execute(
    <any io.reactivex.observers.DisposableObserver>,
    <any java.lang.Void>
);
-> at com.symbol.dataanalytics.domain.features.selfupdate.presenter.TaskPlannerPresenterShould.processSelfUpdate(TaskPlannerPresenterShould.java:41)
Actual invocation has different arguments:
selfUpdateInteractor.execute(
    com.symbol.dataanalytics.domain.features.selfupdate.presenter.TaskPlannerPresenter$SelfUpdateObserver@4f83df68,
    null
);`

I don't understand what mistake i am doing here though i have followed exactly the same you have done .

**Comment by cheflingAnsh** [comment]
Resolved it by 
`  @Test
    @SuppressWarnings("unchecked")
    public void processSelfUpdate() throws Exception {
        presenter.processSelfUpdate();
        Mockito.verify(selfUpdateInteractor).execute(any(DisposableObserver.class), (Void) eq(null));

    }`

Thanks a lot anyway

**Comment by android10** [comment]
Closing since this has been solved!
