### ISSUE TITLE
Build error in Android Studio 1.2 with fully updated sdk

### ISSUE THREAD

**Issue by zob** [android10/Android-CleanArchitecture#21]
Thanks for your great tutorials Fernando. It is a really interesting perspective on android app architechture.
This was just to let you know that I get an error when trying to clone and build this project:
https://gist.github.com/zob/072d6867c43f31c13106

Line 255-258 are shown in a dialog box.

**Comment by android10** [comment]
@zob Thanks so much for the feedback. I really appreciate you found the project useful :).
By the way I bumped the android build tools version and everything seems to be working. At least the CI server did not complain.
Can you check now if works for you?

**Comment by zob** [comment]
@android10 Thanks a lot Fernando. The change to 'com.android.tools.build:gradle:1.2.2' did the trick. Everything is building here now :+1:

**Comment by android10** [comment]
:+1:
