### ISSUE TITLE
Firebase implementation

### ISSUE THREAD

**Issue by adnbal89** [android10/Android-CleanArchitecture#243]
Hello, I'm implementing firebase realtime database to my project but, I get emitter disposed everytime onDataChange() is called, and my UI is not rendering the new list content, here's my code, any suggestions ?

`     @Override
      public Observable<List<SignalEntity>> signalEntityList() {

    Firebase myFirebaseRef = new Firebase("https://mydatabase.firebaseio.com/");

    return Observable.create(emitter -> {

      if (isThereInternetConnection()) {

        myFirebaseRef.child("signal").addValueEventListener(new ValueEventListener() {
          @Override
          public void onDataChange(DataSnapshot snapshot) {
            List<SignalEntity> list = new ArrayList<>();

            Iterable<DataSnapshot> snapshotIterable = snapshot.getChildren();
            Iterator<DataSnapshot> iterator = snapshotIterable.iterator();

            while (iterator.hasNext()) {
              SignalEntity signalEntity = iterator.next().getValue(SignalEntity.class);
              list.add(signalEntity);
            }

            emitter.onNext(list);
            emitter.onComplete();
          }

          @Override
          public void onCancelled(FirebaseError error) {
            emitter.onError(new FirebaseException(error.getMessage()));
          }
        });
      } else {
        emitter.onError(new NetworkConnectionException());
      }
    });
    }`

**Comment by stavelmashally** [comment]
try like this:
`public Observable<List<SignalEntity>> signalEntityList() {
Firebase myFirebaseRef = new Firebase("https://mydatabase.firebaseio.com/");
return Observable.create(emitter -> {
  if (isThereInternetConnection()) {
    myFirebaseRef.child("signal").addValueEventListener(new ValueEventListener() {
      @Override
      public void onDataChange(DataSnapshot snapshot) {
        List<SignalEntity> list = new ArrayList<>();
        for(DataSnapshot child : snapshot.getChildren()){
             list.add(child.getValue(SignalEntity.Class));
        }
        emitter.onNext(list);
      }

      @Override
      public void onCancelled(FirebaseError error) {
        emitter.onError(new FirebaseException(error.getMessage()));
      }
    });
  } else {
    emitter.onError(new NetworkConnectionException());
  }
});
}`
`

**Comment by adnbal89** [comment]
thank you very much for your reply, but i think that my problem is coming from emitter that it has already been disposed somewhere in the code and when we create new emitter and returning back the list of signals, then no other code is observing it. so, i think this progress must be initiated  (i mean the database fetch progress)  with execute command maybe? im so confused on that topic so if you have any ideas please feel free to share. thank you guys.

**Comment by adnbal89** [comment]
Hello @stavelmashally ,

Actually, I figured it out now, basically I call emitter.onComplete() on onDataChange, so emitter gets disposed, and your answer is correct, thank you very much for your correct response. have a nice day.

**Comment by kevin-barrientos** [comment]
@adnbal89 you may close the issue then.
