### ISSUE TITLE
Project will not open at checkout in Android Studio

### ISSUE THREAD

**Issue by RobLewis** [android10/Android-CleanArchitecture#247]
Trying to open this project while checking it out in Android Studio fails. An error message about unknown SDK location appears. 

However, if I answer "No" to the question "You have checked out a project, would you like to open it?", and then later "Open existing project", it works.

**Comment by neslihanturan** [comment]
I am not sure if this is related with the app. Do you experience same issue with different apps?

**Comment by RobLewis** [comment]
I have never before seen a project fail to open immediately after checking it out. This failure is what made me try answering "No", and then later (successfully) opening it. In any case, not a big deal.
