### ISSUE TITLE
Interactor name with verb.

### ISSUE THREAD

**Issue by Hinaka** [android10/Android-CleanArchitecture#258]
@android10 Can I ask about the reason why you decided to change the name from a noun phrase (GetUserDetailUseCase) to a verb phrase (GetUserDetail) in this [commit](https://github.com/android10/Android-CleanArchitecture/commit/0d0a8aefe3f8385e5cb9e0226c33d3601803b115#diff-a2ddc8afab1dd529cfe7a6794ac74bcf)

**Comment by android10** [comment]
It is more meaning to me. You do not need to know that it is a UseCase when the class name is telling you what it does: ```GetUserDetails```. 

I guess it is opinionated but I found shorter names more handy :)

**Comment by Hinaka** [comment]
Thank you for your answer.

**Comment by nanndemoiikara** [comment]
@android10 

Me too felt strange that the class name was a verb.
Why didn't you rename to `UserDetailGetter`?

I would be grateful if you could tell me teach.
