### ISSUE TITLE
Problem with retry api calling.

### ISSUE THREAD

**Issue by Cakirucho** [android10/Android-CleanArchitecture#27]
Hello guys,
When I open the application and have no connection , the window " Retry " appears, if i  press the button, the application blocked and I don't get any response from the server.

I have been researching and I think that when you make the call (this.loadUsers()), if you have no connection, RxJava send you  an onError() message, and you get the window "Retry". Then if you try to make the call again, RxJava don't create any new  thread and it blocks you on "loop" method.

Maybe we should use Retrofit here?

I wonder if it happened to someone else , thank you.

Pd: Sorry for my bad english.

**Comment by rockerhieu** [comment]
Because the presenters are extending `DefaultSubscriber`. When they are either error or complete they can not be reused.

**Comment by Cakirucho** [comment]
Thx, I solved it some days ago.
