### ISSUE TITLE
Why UseCase should be running on other thread? What about synchronous job?

### ISSUE THREAD

**Issue by walsub** [android10/Android-CleanArchitecture#277]
Multithreading is good for the network. disk IO and heavy computing works. 
But if getting small data from local storage on disk IO and pass that data to UI thread, the view can be empty during getting the data. Because there is nothing to display. 

Sometimes I want to get data which is stored only in the local repository and show this data in the first frame of the view. Because UseCase is running on other thread, not main thread, the view is drawn first and updated after received the callback of UseCase.

How can I do that? Does anyone have an idea? 
Should I access the local repository directly on the presenter?

**Comment by mishkaowner** [comment]
Then run the usecase on the uiThread...how simple is that?

**Comment by drayan85** [comment]
You can display something like `Loading in progress...` until the use case returns the result either from a local repository or remote repository.

**Comment by walsub** [comment]
> Then run the usecase on the uiThread...how simple is that?

Thank you for the suggestion. Actually that's what I am doing. :) I was wondering that it's a common situation but why all examples don't execute UseCase in UI thread.

**Comment by walsub** [comment]
> You can display something like `Loading in progress...` until the use case returns the result either from a local repository or remote repository.

Problem was that we don't want to display "something in progress..." when we can use the data immediately at the first frame. The indicator message would be display shortly but it's not good experience I think because it flickers.

**Comment by mishkaowner** [comment]
@walsub well usually UseCase deals with io operations... thats why they r needed to b run on background thread.. if u want to run a usecase on the main thread, there is nothing stops u from doing so... all about case by case

**Comment by walsub** [comment]
> @walsub well usually UseCase deals with io operations... thats why they r needed to b run on background thread.. if u want to run a usecase on the main thread, there is nothing stops u from doing so... all about case by case

Right, I understand that. The point of this question was that I think it's common use case to get the data in the main thread to display the UI in the first frame, of course, this case is happened when there is no default UI for non-existing the cached data. I was wondering that nobody mention this case from blog posts, practices and examples. 

Thank you for your comment and it would be very helpful for me. :)
