### ISSUE TITLE
A branch where dagger is not implemented

### ISSUE THREAD

**Issue by Devofure** [android10/Android-CleanArchitecture#28]
Hi, i was wondering if you could make a branch from the time before you use injection, I just read the "Architecting Android…The clean way?" and it would be great to see the code at that time, Great article by the way.

**Comment by balauru** [comment]
You should be able to go back to a commit,

Looks like https://github.com/android10/Android-CleanArchitecture/commit/f3b7a70129d6475cb849741dd107d39065873847 adds dagger dep.

I will guess that the commit before that has the solution in a state you will require it.

**Comment by Devofure** [comment]
ok, thanks.

**Comment by android10** [comment]
@balauru thanks! That does the trick @Devofure :). And by the way, I create releases before every big change: https://github.com/android10/Android-CleanArchitecture/releases
