### ISSUE TITLE
How would I apply usecases to some kind of background service?

### ISSUE THREAD

**Issue by fernandocamargoti** [android10/Android-CleanArchitecture#29]
I'm trying to use this architecture in my project. In my case, I have a timer that the user will be able to start, pause and stop. We could also think of an example of a music player. In this case, what should be the usecases?

StartTimerUsecase, StopTimerUsecase and so on? All those usecases would point to the same service, right? And, it would need the service to be an actual Android Service, so it could run independent of the UI. How could I manage it?

Thanks in advance.

**Comment by android10** [comment]
The useCases you are pointing out, make sense to me. Then the way you implement them is actually an implementation detail. In your case, instead of hitting a repository, it could get the data from a running service or from any other data source.
