### ISSUE TITLE
Very helpful, but can you show best practices for editing a user?

### ISSUE THREAD

**Issue by jbkielis** [android10/Android-CleanArchitecture#30]
Thanks for the example, extremely helpful.

Would be great to also see the process of editing a user and how that interacts with the cache and the cloud data store.

Thanks again!

**Comment by android10** [comment]
@jbkielis this is meant to be a learning example and I cannot cover all the cases. Remember that pull requests are accepted.

**Comment by jbkielis** [comment]
No problem Fernando.  Just a suggestion as it covers a more realistic use
case.  Thanks again for the tutoring though.  Very helpful!

**Comment by android10** [comment]
@jbkielis it is more about the lack of time. Working on an app that will use this approach and will open source it. It might be a more real case :)

**Comment by jbkielis** [comment]
@android10 Sounds great Fernando.  Thanks for the update.
