### ISSUE TITLE
 Where do WorkManager, JobScheduler Fit In Clean Architecture? 

### ISSUE THREAD

**Issue by KwabenBerko** [android10/Android-CleanArchitecture#304]
Usually, in apps, there are some tasks that we run in the background, such as syncing of data, analytics etc. Google suggested to use deferrable components such as WorkManager and JobScheduler in such situations.
Where do these components fit in Clean Architecture? I'm confused as to where these components belong. Do they belong to the data layer?

**Comment by crjacinro** [comment]
They are all Android specific components so I am thinking they should belong the in the high-level module (UI)
