### ISSUE TITLE
Doubt about source code quality

### ISSUE THREAD

**Issue by dtodt** [android10/Android-CleanArchitecture#33]
First of all sorry for my regular english, it's not my main language.

I found your article interesting and helpful, the best practice in terms of source code organization in my opinion.

What is your opinion about PMD, CheckStyle and FindBugs in Android projects?

I've found an article that explain how to put these tools to work with gradle build.
Here: http://vincentbrison.com/2014/07/19/how-to-improve-quality-and-syntax-of-your-android-code
Source: https://github.com/vincentbrison/vb-android-app-quality

I put it to work with your source code structure, and it works with android based projects, but not with the java project.

Maybe you can help me with that. Could you?

Thanks.

**Comment by android10** [comment]
@dtodt I think code quality is very important and static analysis must be enabled on any software project. Did not started working on that yet but I will do it going forward on this example. Also I have plans to write an article about it.
