### ISSUE TITLE
DaggerCppComponent initialize is empty 

### ISSUE THREAD

**Issue by jien** [android10/Android-CleanArchitecture#38]
Hi,I user dagger2 in my project . I create a component called CppComponent and an activity called LoginActivity. Dagger2 build an implementation class called DaggerCppComponent,but the class DaggerCppComponent's method initialize is empty. It did not init the LoginActivity_MembersInjector class which is built by Dagger2.

**Comment by wsw87201326** [comment]
i have the same question in use dagger2. i can't find DaggerXXComponent in my project.what's happened?

**Comment by android10** [comment]
Closed as not related with the project.
