### ISSUE TITLE
a modified version with MVVM pattern

### ISSUE THREAD

**Issue by weicheng113** [android10/Android-CleanArchitecture#4]
Hi I came across this great sample of clean architecture. I modified the presentation layer to use MVVM pattern based on our [RoboBinding](https://github.com/RoboBinding/RoboBinding) - I have not done the test parts yet. Here is the [link](https://github.com/RoboBinding/Android-CleanArchitecture).

**Comment by Dandewine** [comment]
Thanks, this exact what  I'm looking for.

**Comment by connexion2000** [comment]
Can't wait for MVVM example. Will it be available soon?

**Comment by android10** [comment]
@connexion2000 you can always contribute by sending a PR. :smiley:

**Comment by connexion2000** [comment]
Belive me I would like :)
Unfortunatelly I don't have enough knowledge :)

**Comment by android10** [comment]
@connexion2000 it is a challenge then. We can review your code and help you out.
