### ISSUE TITLE
Json Serializer

### ISSUE THREAD

**Issue by dtodt** [android10/Android-CleanArchitecture#40]
So, whats the deal with the JsonSerializer class? Just asking.

I think you can serialize the UserEntity with the UserEntityJsonMapper, just adding the serializer methods.

I've found another way do use the gson, without use the Type.
Source: http://stackoverflow.com/a/17300003/1703546

I've changed the class methods, and ran the tests and is working fine.

**Entity:**
> UserEntity userEntity = this.gson.fromJson(userJsonResponse, UserEntity.class);

**Entity Collection:**
> final UserEntity[] userEntityArray = this.gson.fromJson(userListJsonResponse, UserEntity[].class);
> userEntityCollection = new ArrayList<>(Arrays.asList(userEntityArray));

**Comment by android10** [comment]
"So, whats the deal with the JsonSerializer class? Just asking."
It is just a decorator in order to not depend on external libraries, thus if you wanna change the serializer you just modify that class.

**Comment by dtodt** [comment]
I've already did that, my question was if this separation was intentional.

In this case, would be a good practice, the serialization be in one class, and the deserialization in another?
Or put all json handle methods in one class.

**Comment by android10** [comment]
For now this fit my needs. I do not want to overthink about this for now. You can refactor later if your class starts becoming a god class.
