### ISSUE TITLE
NullPointerException in mock provided class

### ISSUE THREAD

**Issue by IgorGanapolsky** [android10/Android-CleanArchitecture#41]
Hi,
I am trying to provide a mock implementation of a Retrofit RestAdapter for my unit test.  However, `restAdapter.build();` keeps throwing this exception
> Cannot return null from a non-@Nullable @Provides method

What should I do to resolve this?

Thank you,
Igor

**Comment by android10** [comment]
Closing as not an issue related to this repo. 
Please post your question on stackoverflow.

**Comment by IgorGanapolsky** [comment]
Yes thanks.  My mistake was that I tried to mock RestAdapter with Mockito.
