### ISSUE TITLE
How to get an Object from api instead of array 

### ISSUE THREAD

**Issue by Fshamri** [android10/Android-CleanArchitecture#42]
Hi,
Thanks for this great tutorial. really you help me a lot to learn news ideas specially RxJava and Dagger 2.
I am new to Android and Java but i think, it would be great if you use Retrofit for api calss also Parcelables.

in my case, i have api response comes in objects not in array. so, what changes should i do to receive objects?

Thanks a lot

**Comment by android10** [comment]
Hey @Fshamri this is not meant to be a forum, please post your question on Stackoverflow or similar. 
Closing as not an issue for this project.
