### ISSUE TITLE
UserListPresenter#onUserClicked naming

### ISSUE THREAD

**Issue by mateuyabar** [android10/Android-CleanArchitecture#44]
Hi, very interesting post.

I have a method naming question/issue.

In the UserListPresenter, you have defined a method *onUserClicked(UserModel userModel)*. I'm not sure if this is a correct name. The idea is that the View can change but the presenter remains the same, but the concept of *UserClicked* is something more of the view. Maybe the view changes and the user is displayed in a double click.

In my opinion this method should be called something like *viewUserDetail(UserModel userModel)*.

Thanks,

**Comment by caseykulm** [comment]
The methods that a View calls for it's presenter can be thought of as UI Events. No matter how/where your View shows the button, the Presenter is still concerned with the fact that a UI Event happened, that being the "click" on a user. "viewUserDetail" could also work here, if you were concerned that there is some other UI Event other than "clicking" that could possibly be used to view a user detail.

**Comment by android10** [comment]
@caseykulm good explanation and totally agree. Thanks for clarifying it.
