### ISSUE TITLE
the retry button can not work

### ISSUE THREAD

**Issue by zhl3391** [android10/Android-CleanArchitecture#48]
the retry button can not work

**Comment by lalongooo** [comment]
What do you mean by "cannot work"? You should be more explicit about this. What errors are displayed? What should be the expected behavior?

**Comment by zhl3391** [comment]
When requested data failed,the request cannot retry

**Comment by johnwatsondev** [comment]
Just do debug and try to find root issue. Then commit your PR.

**Comment by lalongooo** [comment]
The retry button works fine for me. Again, without error logs, or messages is hard to know how to solve your issue.

**Comment by zhl3391** [comment]
Oh sorry! I try it again ,the retry button worked,maybe i used the old version before,thank you very much!

**Comment by lalongooo** [comment]
@android10, now you can close this issue.
