### ISSUE TITLE
Packages by feature

### ISSUE THREAD

**Issue by spirosoik** [android10/Android-CleanArchitecture#54]
@android10 I read the article which you have written for this example and I read that you prefer and you suggest to use package by feature. We decided to follow this architecture which you described (with a few changes), but as a DevTeam we want to follow this kind of logic (for ownership) that's why  I want to ask you how it can be this kind of approach for package by feature. 

Let's say I am in Domain layer and I have the following features ```authentication```, ```search```. I will have the followings:
```
com.test.domain.authentication
├─ exception
├─ executor
├─ interactor
├─ repository

com.test.domain.search
├─ exception
├─ executor
├─ interactor
├─ repository
```
Right? The same logic for each layer (data, presentation) in order to be packaged by feature.

**Comment by caseykulm** [comment]
Sounds reasonable, and there may need to be more or less packages added per feature in the future so this isn't a hard set rule. The reason those four packages are likely implemented right inside the domain package for this example project was for simplicity. KISS and scale up when you need to.

You could also do the same thing in reverse as well having each feature implemented once inside each of those four packages (exception, executor, interactor, repository). Either way you're going to end up with 4*(# of features) packages.

**Comment by spirosoik** [comment]
@caseykulm yes I agree it's not a hard rule, I want to understand the main concept that's why I gave this example.

Yeap you are right, maybe this is cleaner than my approach because the main core of packages remains the same.

**Comment by spirosoik** [comment]
I will wait a comment by @android10.

**Comment by android10** [comment]
@spirosoik package by feature as you may know will help you out to no overlap with other teams and touch the same code preventing big conflicted merges. 

Regarding what you pointed out, you are right by grouping functionalities in packages:

```java
com.test.domain.authentication
com.test.domain.search
```

The rest of the packages will depend on the granularity you wanna use:

```
com.test.domain.authentication
├─ exception
├─ executor (this might not be necessary for each feature)
├─ interactor (you can avoid this package and put your use cases right inside the feature)
├─ repository (you can avoid this package and put your repository right inside the feature)

com.test.domain.search
├─ exception
├─ executor (this might not be necessary for each feature)
├─ interactor (you can avoid this package and put your use cases right inside the feature)
├─ repository (you can avoid this package and put your repository right inside the feature)
```

The reason why I used such high granular approach was more for learning purpose. I could get rid of them since each class name defines its purpose and it would not be hard to read and understand.

**Comment by spirosoik** [comment]
@android10 :+1:  excellent thanks for the great info and for the great approach for all stuff. We have already started using the package by feature as you mentioned.

**Comment by android10** [comment]
@spirosoik good to hear that! Looking forward to your thoughts and things you find in your way :)
