### ISSUE TITLE
Parametrize UseCases in the domain layer with some "output" type 

### ISSUE THREAD

**Issue by risayew** [android10/Android-CleanArchitecture#58]
Hi all! Thank you for the interesting project and discussions! I have two questions regrading the "output" type for the use cases in the domain layer. Under the "output" type i mean the type, which will be passed to the presentation layer from the domain layer.

1. In this example project the "User" type(from domain layer) is used as an output type (in GetUserDetails and GetUsetrList UseCases) and will be passed to the presentation layer. Can i pass some another type to the presentation layer? Suppose, some type UserMod, those fields are somehow composed from the User fields. Or this is not correct understanding of the architecture?

2. What we will break, if we parametrize the UseCase abstract class like

``` java
public abstract class UseCase<T> {

protected abstract Observable<T> buildUseCaseObservable();
    
public void execute(Subscriber<T> useCaseSubscriber) { ... }
} 
```
so, a concrete use case will look like:

``` java
public class GetUserDetails extends UseCase<User> {
  
  //constructor here

  @Override protected Observable<User> buildUseCaseObservable() { ... }
} 
```
Thus a subscriber for the use case will be bounded with this "output" type too. Does this make any sense?
Thanks in advance!

**Comment by android10** [comment]
You can use an abstract clase or an interface. Since I did not needed any default implementation I opted for an interface. Always use abstractions no matter what.

You can name your class whatever you want. The important thing is that every layer should deal with its own model, thus, you decouple them.
