### ISSUE TITLE
UserComponent  void inject(UserListActivity userListActivity);

### ISSUE THREAD

**Issue by xiaoniao** [android10/Android-CleanArchitecture#60]
If I added "void inject(UserListActivity userListActivity) " method to UserComponent,It reports an error "Error:(20, 78) 错误: 找不到符号
符号:   类 DaggerApplicationComponent
位置: 程序包 com.fernandocejas.android10.sample.presentation.internal.di.components
/Users/liuzhuang/AndroidStudioProjects/Android-CleanArchitecture10/presentation/src/main/java/com/fernandocejas/android10/sample/presentation/view/activity/UserListActivity.java
Error:(13, 78) 错误: 找不到符号
符号:   类 DaggerUserComponent
位置: 程序包 com.fernandocejas.android10.sample.presentation.internal.di.components
/Users/liuzhuang/AndroidStudioProjects/Android-CleanArchitecture10/presentation/src/main/java/com/fernandocejas/android10/sample/presentation/view/activity/UserDetailsActivity.java
Error:(13, 78) 错误: 找不到符号
符号:   类 DaggerUserComponent
位置: 程序包 com.fernandocejas.android10.sample.presentation.internal.di.components
/Users/liuzhuang/AndroidStudioProjects/Android-CleanArchitecture10/presentation/src/main/java/com/fernandocejas/android10/sample/presentation/internal/di/components/UserComponent.java
Error:(35, 8) 错误: com.fernandocejas.android10.sample.presentation.navigation.Navigator cannot be provided without an @Inject constructor or from an @Provides- or @Produces-annotated method. This type supports members injection but cannot be implicitly provided.
com.fernandocejas.android10.sample.presentation.view.activity.BaseActivity.navigator
[injected field of type: com.fernandocejas.android10.sample.presentation.navigation.Navigator navigator]
4 个错误
Error:Execution failed for task ':presentation:compileDebugJava'.
> Compilation failed; see the compiler error output for details."

**Comment by android10** [comment]
This is not an issue within the repo

**Comment by realkimmy** [comment]
@android10 how to resolve it?
