### ISSUE TITLE
Is there any best practice of how to handle queries?

### ISSUE THREAD

**Issue by risayew** [android10/Android-CleanArchitecture#62]
For example, how to get an artist by email. Extend the UserRepository with Observable<User> getUserByEmail(String email); ?

**Comment by caseykulm** [comment]
Yep, that can work.

**Comment by risayew** [comment]
But is it a good way? Because in this case we put query logic in the data layer. Isn't it so, that the domain layer and data layer can communicating only using CRUD repository?

**Comment by caseykulm** [comment]
There isn't any better layer for data fetching query logic than the data layer. If the email is something the user needs to be able to enter in the presentation layer, and that will end up fetching the User object in the data layer, then what you've suggested makes perfect sense.

**Comment by risayew** [comment]
I also don't have any better idea. But at the same time i don't like the idea of extending the UserRepository interface with the methods like getUserByEmail(String email). Why? Suppose the situation, if as the next we want to query the user by his name. Will we again extend the UserRepository with the method getUserByName(String name)? And by surname, age etc... What about combinations (something like getUserBySurnameAndAgeLessThan(String name, int age))?

**Comment by caseykulm** [comment]
Generally anything that requires user input for data (such as a form, etc.) in the presentation layer in order to obtain data for the current application state from the network/repository in the data layer matches what you are describing, and is the valid and correct way to implement it. 

The only time you should question this pattern is if those fields (such as email, name, age that you mentioned in your examples) are not fetched from user input in the presentation layer.

**Comment by risayew** [comment]
Of course, i mean obtaining the specific data from the data layer and and show it in the presentation layer. 
May be my problem is, that i understand the Repository pattern not in the way meant in this architecture. Repository is 
```
public interface Repository<T>
{
	Observable<T> getById(int id);
	Observable<List<T>> getAll();
	bool add(T entity);
	bool remove(T entity);
}

```

In this case change of the underlying DAL is a simple task. But if we extend the interface implementation with query methods not more so simple, because we have to implement all query methods ...
```
public interface UserRepository extends Repository<User> {
Observable<List<User>> getUsersByAge(int age);
Observable<List<User>> getUsersByMail(String mail);
Observable<List<User>>gettUsersByMailAndAgeLessThan(String mail, int age);
... //more query methods
}
```

As a not optimal solution would be to implement the search according to some criteria in the use case object. But this is for very big price: every time we have to load all users from the data base.

**Comment by caseykulm** [comment]
If things like getUsersByAge are not something that would make up a UseCase directly then they do not belong in the Repository interface. They belong in the factory pattern implementation as a data fetching implementation detail in the data layer. 

If things like getUsersByAge are something that would make up a UseCase directly then they belong in the Repository interface in the domain layer.

**Comment by risayew** [comment]
Makes sense, thank you!
