### ISSUE TITLE
Sometimes AcceptanceTests will fail.

### ISSUE THREAD

**Issue by TerrySunTW** [android10/Android-CleanArchitecture#67]
Sometimes AcceptanceTests will fail.
I think the problem maybe is causing by network delay issue.
The problem will happen when AcceptanceTests verify UI data before getting data processing from internet finished.
It seems test case didn't take care internet delay issue.

**Comment by android10** [comment]
Will close this for now, since they are not failing on the CI. 
A Pull request will be very welcome to solve this issue. Thanks.
