### ISSUE TITLE
Does not import cleanly into Android Studio

### ISSUE THREAD

**Issue by dmfrey** [android10/Android-CleanArchitecture#74]
I can get things running, but all the gradle files report issues and warnings.  Android Studio Project Structure does not resolve any versions.  JUnit test classes aren't decorated as such.

Am I missing something here?

**Comment by android10** [comment]
Can you build via command line?
On Android Studio just import into a new project by picking the main build.gradle file.

**Comment by dmfrey** [comment]
I can build it on the command line.  I did find that I had the wrong build
variant set. Once I set it to Junit, all the unit test stuff resolved fine.

However, look at the Project Settings.  It can't find which version of the
build tools you are using, or the versions of the libraries.  Likewise, in
the build.gradle files, the versions being referenced from build
dependencies are indicating warnings.

**Comment by android10** [comment]
Hey Daniel, thanks for the feedback. The problem that you might be facing is that you do not have installed the build tools version specified in the project build.gradle. 
I will look into this asap.

**Comment by dmfrey** [comment]
Thank you. Let me know if you want me to test anything out.

**Comment by android10** [comment]
@dmfrey I bumped both android build tools and gradle versions. Here is the commit:
https://github.com/android10/Android-CleanArchitecture/commit/57401b29b26d0cb0a7773f8d495930e212faadb0

Will close the issue and we re open if there is someone else having problems.
Thanks for the feedback.
