### ISSUE TITLE
Convention Violation

### ISSUE THREAD

**Issue by sargsyan-garegin** [android10/Android-CleanArchitecture#75]
The `ActivityModule.activity()` method doesn't conform to the provider-method naming convention. Is this on purpose? Isn't `provideActivity()` a better name?

**Comment by android10** [comment]
Here is the article where I explain it: 
http://fernandocejas.com/2015/04/11/tasting-dagger-2-on-android/

```activity()``` in ```ActivityComponent``` is for exposing activities to sub graphs:

```java
@PerActivity
@Component(dependencies = ApplicationComponent.class, modules = ActivityModule.class)
public interface ActivityComponent {
  //Exposed to sub-graphs.
  Activity activity();
}
```

**Comment by yshrsmz** [comment]
I think he is talking about this line.

https://github.com/android10/Android-CleanArchitecture/blob/master/presentation/src/main/java/com/fernandocejas/android10/sample/presentation/internal/di/modules/ActivityModule.java#L37

**Comment by android10** [comment]
@yshrsmz even though that, I'm not providing any activity as far as I remember, when I need a context, there is a provider for it.
