### ISSUE TITLE
Threading with Pool and cgroups

### ISSUE THREAD

**Issue by AndroidGecko** [android10/Android-CleanArchitecture#8]
Hi Fernando,

I really like the architecture.
early P.S - There is no way to register to leave comment on your website so this is why I am writing here.

It would be cool to apply threading priority (see link) to the current architecture
http://www.androiddesignpatterns.com/2014/01/thread-scheduling-in-android.html

Process class which sets priority is an android class.
One possible solution is to make domain layer an android module but would be cool to avoid this.
Is there a way to set this to the thread pool somehow?

As for result handling, I would suggest using callbacks like this 
           done(Result result, Exception e)
instead of two methods 
           onResult(), onError() 
which quickly adds up to verbose code.

let me know what you think

**Comment by android10** [comment]
@AndroidGecko I do not really need threading priority here, It would be over engineering to me. 
In any case if you need it for your architecture, you could fork it and use a very nice library from Path called Priority Job queue:
https://github.com/path/android-priority-jobqueue

**Comment by AndroidGecko** [comment]
@android10 Maybe I didn't express it well, I think you you have different Priority in mind.
The way architecture is working now it is affecting ui thread on heavy load.
please check the link above.

quote from link :

`For the most part, the Android APIs already assign worker threads a background priority for you (for example, see the source code for HandlerThread and AsyncTask). It is important to remember, however, that this will not always be the case. Threads and ExecutorServices that are instantiated on the main UI thread, for example, will inherit a default, foreground priority, making lag more likely and possibly hurting the application's performance. In these cases, you should always remember to set the thread's priority by calling Process.setThreadPriority(Process.THREAD_PRIORITY_BACKGROUND) before the Thread is run`

**Comment by flipper83** [comment]
I like this question
 I believe that it's important for you the performance, you can give support to that with the current code,you can  change the implementation for the interface threadpool, and modify the thread priority on that implementation.

If you believe that this responsability it's part of your usercase, you can take that decision inside of the UserCaseImplementation, you have a collaborator that take the decision for your choise.

I don't know if I responded your question.

**Comment by android10** [comment]
@AndroidGecko I misunderstood your question and I had in mind another concept of priority. This is very interesting information and I will take into account cause I'll be working on some improvements to this in the next few days. :).

@flipper83 good approach!
