### ISSUE TITLE
Rethink Observable.create() ?

### ISSUE THREAD

**Issue by spirosoik** [android10/Android-CleanArchitecture#89]
According to this article [here](http://artemzin.com/blog/rxjava-defer-execution-of-function-via-fromcallable/), they said that: 

> Don't use Observable.create() if you can, it's very easy to shoot yourself in the foot! (and then shoot again for each new subscriber!)

**Comment by android10** [comment]
The guy does not have any argument/reason why not to use it. What makes you think we should not use it?

**Comment by spirosoik** [comment]
Yes you are right there isn't any argument into this post why do not use it. I was wondering if you have any idea why? If you have subscriber and especially in our case we  need the ```create``` to compose the subscriber properly.

But there is a general opinion who says that ([here](http://blog.danlew.net/2015/07/23/deferring-observable-code-until-subscription-in-rxjava/)):

> While the code works now
```java
public Observable<String> valueObservable() {  
  return Observable.create(subscriber -> {
    subscriber.onNext(value);
    subscriber.onCompleted();
  });
}
```
how do I know it will always work for future versions of RxJava? And how do I know I've safely covered all my bases, like backpressure and unsubscription? I'm not an expert on operator development

> Here's an alternative that uses no custom operators:

```java
public Observable<String> valueObservable() {  
  return Observable.defer(() -> Observable.just(value));
}
```
> All I did was wrap the original code with defer(), but now the behavior is what I want. None of the code inside of defer() is executed until subscription. We only call Observable.just() when someone requests the data.

> I prefer this solution for a couple reasons:

>  It's simpler than Observable.create() - no need to call onCompleted().
It uses built-in operators, so they're (probably) implemented correctly.
The only downside to defer() is that it creates a new Observable each time you get a subscriber. create() can use the same function for each subscriber, so it's more efficient. As always, measure performance and optimize if necessary.

I think our case is different here. We do almost the same because we execute the code when there is a subscriber

**Comment by android10** [comment]
I don't think is a big deal here. The article refers to the fact that by using Observable#create is easier to break the Observable contract and if you do not care about it, you might end up creating Observables that may never complete.

**Comment by spirosoik** [comment]
Yes it's not a big deal, basically it's an abstraction, in our case we must have every thing of subscriber.

Thanks for the discussion man!

**Comment by artem-zinnatullin** [comment]
Hello there :smile: 

>I don't think is a big deal here. The article refers to the fact that by using Observable#create is easier to break the Observable contract and if you do not care about it, you might end up creating Observables that may never complete.

Exactly, I saw some implementations of `Observable.create` that had different problems and errors. Basically, if you can avoid `Observable.create ->` avoid it, but if you 100% sure you need it — no problem.

`Observable.fromCallable(() -> some code)` handles a lot of cases, it's probably a most used operator in our code for creating Observables.

**Comment by android10** [comment]
@artem-zinnatullin nice observation. The only thing I would add is that defer() operates in a different way than create(). You might need the Observable to be created right away (create) and not when someone subscribes to it, or the other way around.

**Comment by spirosoik** [comment]
@artem-zinnatullin @android10 Yes I think that's the point which he tried to explain into the article, maybe it's not obvious. He noticed that he didn't want to create an ```Observable```  when someone subscribed to it.
