### ISSUE TITLE
Considering activity lifecycle 

### ISSUE THREAD

**Issue by misrakli** [android10/Android-CleanArchitecture#9]
Hi,
first of all thank you for your work.
One think i didn't understand is how to deal with the lifecycle of the activities related to the jobexecutor as the jobs are running in a threadpool and i need the possibility to cancel a job (while navigating through activities).
Can you give an example how you would integrate for example Loaders (or is using loaders not a good approach in this architecture) or RxJava?
Another question is, when and how to cleanup references (like callback in interactor, when presenter is no more interested in interactor results).

**Comment by android10** [comment]
If you need to cancel jobs you can consider using https://github.com/path/android-priority-jobqueue from Path. 
This sample is a starting point and I did not think in all cases cause it does not make sense yet, so if you solve that problem, you can do a pull request :)
