### ISSUE TITLE
Long running Use Case and orientation change

### ISSUE THREAD

**Issue by mack369** [android10/Android-CleanArchitecture#90]
In the current approach, every time after the orientation changes, the use case is executed once again. It would be a good solution if there would be a way to reuse the current operation after the orientation change, if the previous one is still running

**Comment by Trikke** [comment]
You are welcome to provide a PR with a valid implementation.

**Comment by Rainer-Lang** [comment]
+1

**Comment by android10** [comment]
@Trikke :+1:

**Comment by lenguyenthanh** [comment]
Any good ideal for this enhancement? I really want to help to solve this problem.

**Comment by Fshamri** [comment]
+ 1

**Comment by spirosoik** [comment]
:+1:

**Comment by alexandru-calinoiu** [comment]
@lenguyenthanh I suppose a good starting point will be the classical Headless Fragment or maybe there are some later additions to the android framework that I've missed.

**Comment by android10** [comment]
This is weird since the easiest solution would be to retain the fragment instance and indeed I'm doing that. This needs a little bit of investigation.

**Comment by android10** [comment]
This was fixed here:
https://github.com/android10/Android-CleanArchitecture/commit/ee50c079b4d60e5545f2d50cf1eb167e75d1c2c8

**Comment by Rainer-Lang** [comment]
@android10 I don't want to open a new issue right now. Maybe it could be handled here....
Following usecase:
1) user: backpress/leaves activity
2) save/upload data to server -> potentially long running task

Maybe you could give me a hint....
